### ISSUE TITLE
GengtuUpload

### ISSUE THREAD

**Issue by YuzhoUniverse** [HelloGwkki/GengTu#7]
[IMAGE LINK]
https://z3.ax1x.com/2021/05/09/gY1Fv6.png

[DESCRIPTION]
2222222222

[PEOPLES]
拉丝

[QQ ID]
1562628641

=w=

**Comment by HelloGwkki** [comment]
谢谢宇宙！
不过请不要在已经创建好Gengtu提交的时候再次编辑
